### ISSUE TITLE
1.7

### ISSUE THREAD

**Issue by Eufranio** [games647/LagMonitor#16]
Please make it compatible with 1.7 modded servers :/

**Comment by games647** [comment]
Aren't there other similar plugins (including paid ones) which can run in a 1.7 server? 

As I told you in the other ticket. Manye things have to be changed, because:
1. The bungeeCord textcomponent isn't included
2. The timings system was refactored (affects the /timing and /paper commands)
3. The dependency (i.e. guava) versions were updated
4. Deprecated methods like Player[] getOnlinePlayers() were removed
5. Modding servers have a different code base. Although many features uses only the bukkit/spigot API or Java MX API (included in Java), some others accesses the internal code like the timings and the ping command (ping **could** be compatible with MCPC/Cauldron)

Besides that, not many server are still running 1.7, so it's worth spending my time for it as I'm running this project for free.
