### ISSUE TITLE
Compatibility with MobHunting

### ISSUE THREAD

**Issue by Rocologo** [games647/LagMonitor#21]
Im the dev. of MobHunting and one my users @Maxetto has raised an issue. The user has used my plugin for a long time now without problems, but then he installed LagMonitor and then my plugin failed. If he removes LagMonitor my plugin works again. 

@Maxetto  has noticed that I uses the newer method MySQLDataSource than the older DriverManager which of cause should be fine and it works perfectly except when LagMonitor is installed.

**Comment by games647** [comment]
Do you have any errors? I guess there is some class loading issues.

**Comment by Maxetto** [comment]
http://pastebin.com/T3R46YtB

**Comment by Rocologo** [comment]
Yes, I forgot to reference the ticket https://github.com/Rocologo/MobHunting/issues/108 but I see Maxetto found the link for you. ☺

**Comment by games647** [comment]
>@Maxetto has noticed that I uses the newer method MySQLDataSource than the older DriverManager which of cause should be fine and it works perfectly except when LagMonitor is installed.

It's because you make blocking sql connection on the player join. This triggers LagMonitor and it tries to find the source plugin. There it finds a native JVM class which cannot be loaded with Class.forName and then creates a ClassNotFoundException in LagMonitor.  

This happens while making the first SQL request. So it's wrapped with a SQLException. You're error message: https://github.com/Rocologo/MobHunting/blob/master/src/one/lindegaard/MobHunting/storage/MySQLDataStore.java#L55

is very misleading. Next time you should use multi catches, because even with incorrect username/password combination it would print "MySQL not present on the classpath". Furthermore it's good way to always print the original stacktrace. It's a lot easier to debug it. 

In your case you could also wrap it with your exception using DataSourceException(String, Exception)

**Comment by Maxetto** [comment]
Fix confirmed ;)

**Comment by Rocologo** [comment]
Thank you for making the pull requests, I merged them. I will try to remove the blocking sql connection on playerjoin as well.
